export { ProjectTEDEditContent } from "./edit/ProjectTEDEdit"
export { DEFAULT_FORM_SECTION, PROJECT_FORM_SECTIONS } from "./forms"
export type { ProjectFormSectionProps } from "./forms"
export { mapModeloCronogramaToForm, statusToStepIndex, STATUS_PROJETO_STEPS } from "./services/projectTED.service"
export type { ProjectModelData, CronogramaDataMapped } from "./services/projectTED.service"
